apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  labels:
    app: httpd
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    #server: 172.17.0.116
    # Exported path of your NFS server
    #path: "/mnt/mnt1"
